version: "2"
services:
  mautic:
    restart: unless-stopped
    image: mautic/mautic
    depends_on:
      - mysql
    ports:
      - "80:80"
    environment:
      MAUTIC_DB_HOST: mysql
      MAUTIC_DB_USER: mautic
      MAUTIC_DB_PASSWORD: mauticdbpass
      MAUTIC_TRUSTED_PROXIES: 0.0.0.0/0
    volumes:
      - mautic-web:/var/www/html

  mysql:
    restart: unless-stopped
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
      MYSQL_DATABASE: mautic
      MYSQL_USER: mautic
      MYSQL_PASSWORD: mauticdbpass
    volumes:
      - mysql:/var/lib/mysql
      
volumes:
  mautic-web:
  mysql:
